Bosheng
Enraged-Dun-Cookie-Development-Team/Ceobe-bot pull request #2
Opened 2023-07-05 01:33 UTC by Bosheng0422

Fin  添加负责人 查询负责人 删除负责人

Format 
@bot 添加负责人/删除负责人 端名 @用户 
@bot 查询负责人 端名
eg. @小刻-测试中 添加负责人 RUST @薄生 / @小刻-测试中 查询负责人 RUST

端名：RUST FETCHER ANALYZER SCHEDULER

2023-07-05 10:21 UTC, phidiaLam requested changes

2023-07-05 10:21 UTC, phidiaLam commented on initialize/bot.go
> +
这段没用了删掉吧

2023-07-05 10:21 UTC, phidiaLam commented on initialize/bot.go
> +	fmt.Println(string(data))
删掉不必要的print？

2023-07-05 10:21 UTC, phidiaLam commented on conf/maintainers.json.sample
程序生成的配置不需要sample

2023-07-05 10:21 UTC, phidiaLam commented on conf/maintainers.json
这个git rm -f <文件路径>删掉一下git里面的这个文件

2023-07-07 09:56 UTC, merged

2023-07-07 09:56 UTC, Bosheng0422 commented on initialize/bot.go
> +	fmt.Println(string(data))
删了

2023-07-07 09:56 UTC, Bosheng0422 commented on conf/maintainers.json.sample
明白